services:
  postgres:
    image: postgres:16
    container_name: postgres-dev
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devopsplatform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"
    networks:
      - app-net

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend-dev
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - app-net

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
