apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: backend
    project: production-devops-platform
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.backend.springProfile | quote }}
