{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: production-platform-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    project: production-devops-platform
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: /students
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
