# Helm encodes the plaintext values from values.yaml using the b64enc function.
# This means values.yaml stores plain text, and Helm produces the correct base64 Secret.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: postgres
    project: production-devops-platform
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | b64enc | quote }}
